---
title: "01_summaries"
author: "Puvvula"
date: "2023-03-02"
output: pdf_document
---

```{r}
library(tidyverse)
library(janitor)
library(haven)
library(skimr)
library(readr)
library(reshape2)
library(kableExtra)
library(gridExtra)
```

survey data
```{r}
dt_survey <- read_sas("~/Documents/MWAS_home/Covariates/analysis_data.sas7bdat") |>
  clean_names() |>
  mutate_if(is.character, ~na_if(.,"")) |>
  select_if(~ mean(is.na(.)) < 0.2) |> # drop variables > 20% missing
  select_if(~ !(is.numeric(.) && all(. == 0)) & mean(. == 0, na.rm = TRUE) < 0.8) |> # drop all variables with zeros
  mutate_if(is.character, as.factor) |>
  select(-c(matblood, urine, placenta)) |>
  mutate(dist_majhw_cat = case_when(
    dist_majhw == "Less than 500 feet" | dist_majhw == "500 feet to 1/2 mile"~ 1,
    dist_majhw == "1/2 mile to 1 mile" ~ 2,dist_majhw == "More than 1 mile" ~ 3,
    is.na(dist_majhw) ~ NA_real_,TRUE ~ NA_real_))  # leve-1: lessthan 0.5 mi., level-2: 0.5-1 mi., level-3: >1 mi.
  

skim(dt_survey)

```


```{r}
#Urine PAH concentration (log transformed and creatinine adjusted) + covariates
mom_pah<- read_csv("~/Documents/MWAS_home/pj_dat/mom_pah.csv") |>
  clean_names()|>
  mutate_at(vars(3:11), ~log(. + 1))

#Creatinine adjustment
ur_cr<- read_csv("~/Documents/MWAS_home/pj_dat/ur_creat.csv") |> 
  select(c(2,3)) |> 
  rename(group="id", mom_ur_ct = "urine_crt") |>
  mutate(lg_ur_cr_ng = log(mom_ur_ct*100)) #converted mg/dl -> ng/L and on log scale

pah<- pah |> left_join(ur_cr, by="group")

#PAH concentration / log creatinine (ng/L) to yield PAH in ng/g cr units
pah<- pah |>
  mutate_at(vars(3:11), ~ . / lg_ur_cr_ng)

#===============================================================================

baby_pah<- read_csv("~/Documents/MWAS_home/pj_dat/baby_pah.csv") |>
  clean_names()|>
  mutate_at(vars(13:21), ~log(if_else(is.na(.), 1, .) + 1))

covar <-read_csv("~/Documents/MWAS_home/pj_dat/covar.csv") |>
  clean_names()

covar[c(11:15)]<- lapply(covar[c(11:15)], as.numeric)

#####################################################################
#join mom and baby PAH
pah<- full_join(mom_pah, baby_pah[1:11], by="group") |>
  rename(participant_id_mom = "participant_id.x" ,
         participant_id_baby = "participant_id.y")

pah_fin<- full_join(pah, covar[-c(1,7)], by="group")

write_csv(pah_fin, "~/Documents/MWAS_home/pj_dat/pah_fin.csv")


```

imputing missing data
```{r}
mom_pah<- read_csv("~/Documents/MWAS_home/pj_dat/pah_fin.csv") |>
  mutate(mom_edu_cat = if_else(mom_edu == "Bachelor's degree" | mom_edu == "Master's degree or above", "bach-or-abv", "lt-bach")) |>
  mutate(mom_edu_cat = if_else(is.na(mom_edu_cat), "lt-bach", mom_edu_cat)) |>
  mutate(race_cat = if_else(mom_race == "Non-Hispanic White", "white", "non-white")) |>
  mutate(mom_age = if_else(is.na(mom_age), median(mom_age, na.rm = TRUE), mom_age)) |>
  mutate(mom_ppbmi = if_else(is.na(mom_ppbmi), median(mom_ppbmi, na.rm = TRUE), mom_ppbmi)) |>
  mutate(totpg = if_else(is.na(totpg), median(totpg, na.rm = TRUE), totpg)) |>
  mutate(babywt_g = if_else(is.na(babywt_g), median(babywt_g, na.rm = TRUE), babywt_g)) |>
  mutate(csec = if_else(is.na(csec), "Yes", csec)) |>
  select(-c(mom_edu, mom_race))

write_csv(mom_pah, "~/Documents/MWAS_home/pj_dat/pah_fin_impu.csv")
```


summary table
```{r}
dat_wide<- read_csv("~/Documents/MWAS_home/pj_dat/pah_fin.csv") |>
  select(c(1,3:20)) |>
  pivot_longer(!participant_id, names_to = "measure", values_to = "value") |>
  mutate(mom_baby = substr(measure, 1, 1))

geomean <- function(x, na.rm = T, trim = 0, ...) 
  { exp(mean(log(x, ...), na.rm = na.rm, trim = trim, ...)) }
geosd <- function(x, na.rm = T, ...)
{ exp(sd(log(x, ...), na.rm = na.rm, ...)) }

dat_summ<- dat_wide |> 
    group_by(measure, mom_baby) |>
    summarise(geometric_mean = geomean(value), geometric_SD = geosd(value),
              median = median((value), na.rm = T), q25 = quantile(value, .25, na.rm=T),
              q75 = quantile(value, .75, na.rm=T)) |>
    mutate_if(is.numeric, round, 3)

pah_tab<- kable(dat_summ, longtable=T, booktabs=T, caption = "PAH - Data summary") |>
  kable_styling(latex_options = c("repeat_header"))

write_csv(dat_summ, "~/Documents/MWAS_home/pj_dat/pah_summary.csv")
```

correlation b/w chemicals mom and baby
```{r}
dat<- read_csv("~/Documents/MWAS_home/pj_dat/pah_fin.csv") |>
  select(1:21) |>
  drop_na()

cormat<- round(x=cor(dat[c(3:11,13:21)], method = "spearman", 
                     use= "complete.obs"), digits=2) |>
  melt() |> clean_names()

###############################################################################
#run this only if interested in certain combinations
cormat<- cormat |> 
  mutate(pair_cat= paste0(substr(var1, 1, 1), substr(var2, 1, 1))) |>
  filter(pair_cat == "mb")
###############################################################################

ggplot(cormat, aes(x=var2, y=var1, fill=value, label=value)) +
  geom_tile(color = "white") +
  geom_text(color = "black", size = 5, vjust = 1) +
  scale_fill_gradient2(low="red", high="blue", mid="white",
                       midpoint=0,
                       limit=c(-1,1), space= "Lab",
                      name="Spearman Correlation")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1),
        axis.text.y = element_text(angle = 0, vjust = 1, size = 12, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom", legend.box = "horizontal")+
  coord_fixed()
```

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

