---
title: "06_pathway_enrich_figs.Rmd"
author: "Puvvula"
date: "2023-03-14"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor)
```

```{r}
pathways<- read_csv("~/Documents/MWAS_home/pj_result/mummi_import_combined.csv") |>
  clean_names()|>
  rename(p_fisher = "fet",
         name= "x") |>
  mutate(mom_baby = fct_recode(mom_baby,
                               "Maternal" = "mom",
                               "Newborn" = "baby"))

#p_fisher = one-tailed Fisher Exact Test p-value (based on Gaussian hypergeometric probability distribution)
#p_ease = EASE score (a conservative adjustment to the Fisher exact probability that weights significance in favor of themes supported by more hits) Expression Analysis Systematic Explorer
#p_gamma = Gamma p values - using Gamma distribution to model permutation results

plot.mcg <- pathways |> 
  filter(p_fisher < 0.05) |>
  mutate(logp = -log10(p_fisher), enrichment = hits_sig/expected, 
         pct_sig_hits = (hits_sig/pathway_total)*100) |>
  mutate(pct_sig_hits_disc = cut(pct_sig_hits, breaks = seq(0, 90, by = 15), 
                                 labels = c("< 15", "15 - <30", "30 - <45", 
                                            "45 - <60", "60 - <75", "75 - <90"))) |>
  filter(pathway_total > 1)

# Rename labels for maternal and newborn
# Update the levels of fact_new with new labels
#plot.mcg$fact_new <- factor(plot.mcg$fact_new, levels = c("baby-neg", "baby-pos", "mom-neg", "mom-pos"),labels = c("Newborn C18", "Newborn HILIC", "Maternal C18", "Maternal HILIC"))

#########################################
my_colors <- colorRampPalette(c("#F8766D", "#7CAE00"))(6)

# Create a new column with the cluster labels
plot.mcg$metabolism_cluster <- ifelse(grepl("metabolism", plot.mcg$name, ignore.case = TRUE), "metabolism",
                                      ifelse(grepl("biosynthesis", plot.mcg$name, ignore.case = TRUE),
                                             "biosynthesis",
                                             ifelse(grepl("oxidation", plot.mcg$name, ignore.case = TRUE),
                                                    "oxidation", 
                                                    ifelse(grepl("degradation", plot.mcg$name, ignore.case = TRUE),
                                                           "degradation","na"))))


# Creating new variable to cluster y axis
plot.mcg <- plot.mcg %>%
  mutate(group = case_when(
    grepl("Vitamin", name, ignore.case = TRUE) ~ "vit",
    grepl("fatty acid|Arachidonic|Carnitine|Phytanic|Butanoate|Glycerophospholipid", name, ignore.case = TRUE) ~ "fatty",
    grepl("steroid|androgen", name, ignore.case = TRUE) ~ "ster",
    grepl("porphyrin|Pyrimidine|Purine|Glyoxylate", name, ignore.case = TRUE) ~ "organic",
    grepl("Methionine|Glutamate|Glycine|Beta-Alanine|Arginine|Glutathione|Aspartate|Lysine|Tyrosine|Alanine|Tryptophan|Histidine",
          name, ignore.case = TRUE) ~ "amino",
    grepl("Galactose|Fructose|Pentose", name, ignore.case = TRUE) ~ "sug",
    TRUE ~ "other"
  ))

plot.mcg$group<- factor(plot.mcg$group, levels = c("vit", "amino", "sug", "fatty", "ster", "organic"))

#export results csv
write_csv(plot.mcg, "~/Documents/MWAS_home/pj_result/plot_mcg.csv")

# Reorder y-axis based on the cluster labels
plot.mcg |>
  ggplot(aes(x = factor(chemical, levels = c("1-Hydroxynapthalene", "2-Hydroxynapthalene", "2-Hydroxyfluorene",
                                              "1-Hydroxyphenanthrene", "2,3-Hydroxyphenanthrene",
                                             "4-Hydroxyphenanthrene","9-Hydroxyphenanthrene", 
                                             "sigma-LMWT-PAH", "1-Hydroxypyrene")), 
             y = name)) + 
  geom_tile(aes(fill = factor(pct_sig_hits_disc)), color = "black") +
  scale_color_manual(values = my_colors) +
  xlab("") +
  ylab("") +
  theme_bw() +
  theme(axis.text=element_text(size=10), 
        axis.title=element_text(size=10,face="bold"),
        strip.text = element_text(size=10),
        legend.text=element_text(size=10),
        legend.title=element_text(size=10),
        legend.position="bottom",
        legend.justification="right",
        legend.box="horizontal",
        legend.box.just="center",
        legend.margin=margin(t=0.1, r=0.1, b=2, l=0.1),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.x = element_text(angle = 40, hjust = 1, vjust = 1, size = 10),
        axis.text.y = element_text(size = 10), 
        panel.spacing.x=unit(0.8, "lines"),
        panel.spacing.y=unit(0.02, "lines"),
        strip.text.y = element_blank())+
  guides(fill = guide_legend(nrow = 1))+
  facet_grid(factor(metabolism_cluster, levels = c("metabolism", "oxidation",
                                                   "degradation", "biosynthesis", "na"))*group~ mom_baby, scales = "free_y", 
             switch = "y", space = "free_y")+
  labs(fill = "% significant hits per pathway")

ggsave("~/Documents/MWAS_home/pj_result/pah_pathway.tiff", 
       width = 8, height = 10, dpi=300)
```

#Venn diagram
```{r}
library(ggupset)
data<- read_csv("~/Documents/MWAS_home/pj_result/plot_mcg.csv")|>
  filter(mom_baby=="Maternal")|> 
  select(name, chemical)

#plot that doesnt provide set size
data |>
  group_by(name) |>
  summarize(chemicals=list(chemical)) |>
  ggplot(aes(x=chemicals)) +
  theme_bw()+
  geom_bar()+
  scale_x_upset(order_by = "degree")
  

#### with the set size
library(UpSetR)
data %>%
  distinct(name, chemical, .keep_all=TRUE) %>%
  unnest(cols = chemical) %>%
  mutate(GenreMember=1) %>%
  pivot_wider(names_from = chemical, values_from = GenreMember, values_fill = list(GenreMember = 0)) %>%
  as.data.frame() %>%
  UpSetR::upset(sets = c("1-Hydroxypyrene", "sigma-LMWT-PAH", "9-Hydroxyphenanthrene", 
                         "4-Hydroxyphenanthrene", "2,3-Hydroxyphenanthrene", "1-Hydroxyphenanthrene",
                         "2-Hydroxyfluorene", "2-Hydroxynapthalene", "1-Hydroxynapthalene"), 
                keep.order = TRUE, set_size.show=TRUE,
                order.by = "freq", text.scale = 2, point.size = 3, line.size = 1.3,
                set_size.scale_max = 30, mainbar.y.max=20,
                mainbar.y.label="No.of Overlapping pathways \nacross chemicals", 
                sets.x.label="Total no.of pathways \nper chemical")



```



# Summary tables for publication text
```{r}
#total pathways associated with PAH
n_distinct(pathways$name)
# significant number of pathways associated with PAH
n_distinct(plot.mcg$name)

x<-plot.mcg |>
  group_by(fact_new, chemical) |>
  summarise(n_unique_names = n_distinct(name),
            uniq_pct = round((n_distinct(name)/54)*100,2))

#times per baby_mom per pos_neg a pathway repeated
y<-plot.mcg |>
  group_by(name,fact_new) |>
  summarise(times_repeat = n())

z<-plot.mcg |>
  group_by(chemical,fact_new) |>
  summarise(times_repeat = n())
```





