---
title: "02.1_filter_by_corr"
author: "Puvvula"
date: "2023-03-15"
output: pdf_document
---

#Function to genrerate correlation coefficients for chemical and m/z features 
```{r}
my_function <- function(data_list, covariates, variables, output_dir, data_list_name) {
  result_list <- list()
  for (i in seq_along(data_list)) {
    current_results_list <- list()
    data_name <- data_list_name[i] # get the name of the current data frame
    for (variable in variables) {
      current_results <- data.frame(matrix(nrow = nrow(data_list[[i]]), ncol = 3)) 
      # create a new data frame for each variable
      names(current_results) <- c("Correlation", "p-value", "FDR")
      for (j in 1:nrow(data_list[[i]])){
        metabolite <- unlist(data_list[[i]][j,-c(1:2)]) # store the jth metabolite in new vector
        cor_res <- cor.test(metabolite, covariates[[variable]], method = "spearman") 
        # perform Spearman correlation test
        current_results[j,1:2] <- cor_res[c("estimate", "p.value")] # store correlation coefficient and p-value
        }
      current_results$FDR <- p.adjust(current_results[[2]], method=c("fdr")) # fdr adjustment
      current_results <- cbind(data_list[[i]][c(1:2)], current_results) # add mz and time
      current_results$Variable <- variable
      current_results_filtered <- current_results %>%
        filter(Correlation > 0.3 & `p-value` < 0.05) # filter results
      current_results_list[[variable]] <- current_results_filtered # add current results to list
      file_name <- paste0(variable, "_", data_name, ".csv") # generate file name by combining variable and data name
      write.csv(current_results_filtered, file.path(output_dir, file_name), row.names = FALSE) 
      # save results as csv file
      }
    result_list[[data_name]] <- current_results_list # add current results to list
    }
  return(result_list)
  }
```


#provide inputs
```{r}
data_list_name <- c("c18_neg", "hilic_pos")
data_list <- list(c18_neg, hilic_pos) # list of data frames to analyze
variables <- names(covariates[2:10]) # list of variables to analyze
output_dir <- "~/Documents/MWAS_home/cor_test" # specify the output folder


my_function(data_list, covariates, variables, output_dir, data_list_name)
```

